#!/usr/bin/env python3
# vim:fileencoding=utf-8
# License: GPL v3 Copyright: 2017, Kovid Goyal <kovid at kovidgoyal.net>

import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from contextlib import suppress

# EOF_REMOTE

HOST = 'ubuntu'

base = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, base)
from kitty.constants import str_version

tarball = f'kitty-{str_version}-x86_64.txz'


def run(what):
    ret = subprocess.run(shlex.split(what))
    if ret.returncode != 0:
        raise SystemExit(ret.returncode)


with open(__file__, 'rb') as f:
    script = f.read().decode('utf-8')
script = script[:script.find('# EOF_REMOTE')].replace('if False:', 'if True:', 1)
with tempfile.NamedTemporaryFile(prefix='install-tarball-', suffix='.py') as f:
    run('python ../bypy linux program --dont-strip --compression-level=1')
    f.write(script.encode('utf-8'))
    f.flush()
    run(f'scp bypy/b/linux/64/sw/dist/{tarball} {f.name} {HOST}:/tmp')
    run(f'ssh {HOST} python /tmp/{os.path.basename(f.name)} /tmp/{tarball}')
